/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zjf_ffmpeg_FFmpeg */

#ifndef _Included_com_example_zjf_ffmpeg_FFmpeg
#define _Included_com_example_zjf_ffmpeg_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zjf_ffmpeg_FFmpeg
 * Method:    addBgm
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_zjf_ffmpeg_FFmpeg_addBgm
  (JNIEnv *, jobject, jstring, jstring, jstring);
#ifdef __cplusplus
}
#endif
#endif
